# fastlane/Fastfile
# android
previous_build_number = google_play_track_version_codes(
  package_name: "#{ENV['ANDROID_PACKAGE_NAME']}",
  track: "beta",
  json_key: "#{ENV['GOOGLE_PLAY_KEY_FILE']}",
)[0]

current_build_number = previous_build_number + 1

increment_version_code(
  gradle_file_path: gradle_file_path,
  version_code: current_build_number
)

platform :android do
  desc "Upload a new Android version to the Google Play Store"
  lane :beta do
    upload_to_play_store(track: 'beta',release_status: 'completed',aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
  end
end
