name: Discord Webhook

on: [push]

jobs:
  build:
    name: Update Discord
    runs-on: ubuntu-latest 
    steps:
      - name: bot
        uses: sarisia/actions-status-discord@v1.8.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true

          title: "***New Update on itch:*** https://tycro-games.itch.io/lunar-voyage-moon-colonization"
          description: ${{github.event.head_commit.message}}
        # image: ${{ secrets.EMBED_IMAGE }}
          color: 0xffffff
          username: Your friendly spiderman
      #    avatar_url: ${{ secrets.AVATAR_URL }}